application: consolejson
version: 1
runtime: php
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: home/index.php

- url: /home/
  script: home/index.php

- url: /docs/
  script: docs/index.php

- url: /demo/
  script: demo/index.php

- url: /about/
  script: about/index.php
